# D. E. U. en Inteligencia Artificial de Samsung Innovation Campus (Exercises)

- Cèsar Ferri, `cferri@dsic.upv.es` (Introducción).
- Javier Palanca, `jpalanca@dsic.upv.es` y Salvador España, `sespana@dsic.upv.es` (Numpy, Pandas).
- **`Mayús` + `Tab`**: shows the help of the function, in addition to the `help()` function.
- **`Esc` -> `M`**: changes the cell to Markdown (**Y** to change to Code).
- **`Tab` MUST BE USED**.

# Chapter 1. Introduction

- 

# Chapter 3. Numpy and Pandas (Optimized Numerical Computation)

## Unit 1. Numpy Array Data Structure for Optimal Computational Performance

In [160]:
import numpy as np

x = np.arange(1, 7)
print(x)
print(x.reshape(2, -1))
print(x.reshape(3, -1), end="\n\n")

# Forma de inicializar el generador de números semi-aleatorios (pues al final no son tan aleatorios)
np.random.seed(125)

np.random.randint(10)                      # Genera número random de 0 a 10
np.random.randint(5, 10)                   # Genera número random de 5 a 10
np.random.randint(4, 10, size=(3, 2))      # Genera un array de números de 4 a 10, de 3 elementos en 2 dimensiones
np.random.randint(1, 11, size=1000)        # Genera un array de 1000 elementos aleatorios

A = np.arange(4).reshape(2, 2)             # One-line matrix array creation
print("A = ", A)
B = np.arange(3, -1, -1).reshape(2, 2)
print("B =", B, end="\n\n")

print(A.dot(B))                            # Matrix multiplication using dot
print(A @ B)                               # Matrix multiplication using @
print("Transpose of A =", A.transpose())   # Transponding matrixes
print(np.linalg.det(A), end="\n\n")        # Determinant of matrix A

b = np.arange(12).reshape(3, 4)
print(b)
print(b[0][2])                             # Matrix indexing way 1
print(b[0, 2])                             # Matrix indexing way 2
b[0, 2] = -1                               # Matrix element manipulation
print(b[0, 2])
print(b[[0, 1]])                           # Double [[]] return several given values
print(b[[0, 2], [0, 1]], end="\n\n")       # Returns the elements [0, 0] and [2, 1] of the matrix (BEWARE!)

y = np.arange(1, 7)
print(y[y > 3], end="\n\n")                # Returns the elements that GAVE TRUE to the given condition

arr2d = np.arange(1, 10).reshape(3, 3)
print(arr2d)
print(arr2d[:2])                           # First 2 rows
print(arr2d[:2, 1:])                       # First 2 rows, last 2 columns
print(arr2d[:, :1], end="\n\n")            # All rows, first column

names = np.array(['Bob', 'Joe', 'Tom', 'Bob', 'Joe', 'Tom', 'Joe'])
print(repr(names[names=="Bob"]), end="\n\n")# Returns all elements equal to "Bob"

arr = np.empty((8, 4))                     # Creates an array matrix with uninitialized values
print(arr)
arr2 = np.zeros((8, 4))                    # Creates a zeroed array matrix
arr3 = np.ones((8, 4))                     # Creates a ones array matrix
print(arr2, arr3, end="\n\n")

arr4 = np.arange(20)
arrMask = arr4 % 5 == 0                    # Mask of values divisible by 5
print(arr4[arrMask])                       # Returns elements divisible by 5
arrMask2 = arr4 >= 10                      # Mask of values >= 10
print(arr4[arrMask & arrMask2], end="\n\n")# Applies two masks

arr5 = np.arange(15).reshape(3, 5).T       # T used as np.transpose()
print("arr5", arr5, end="\n\n")
arr6 = np.arange(12).reshape(3, 4).transpose(0, 1)
print("arr6", arr6, end="\n\n")

# In the following case, the dimensions are exchanged, from (0, 1, 2) to (1, 0, 2)
arr7 = np.arange(16).reshape(2, 2, 4)
print("arr7", arr7)                        # 2 depth, 2 rows, 4 cols
print("arr7b", arr7.transpose(1, 0, 2))    # Swap first 2 axes
print("arr7c", arr7.transpose(2, 1, 0), end="\n\n")  # Swap axes to (2, 1, 0)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]

A =  [[0 1]
 [2 3]]
B = [[3 2]
 [1 0]]

[[1 0]
 [9 4]]
[[1 0]
 [9 4]]
Transpose of A = [[0 2]
 [1 3]]
-2.0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
2
-1
[[ 0  1 -1  3]
 [ 4  5  6  7]]
[0 9]

[4 5 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[1]
 [4]
 [7]]

array(['Bob', 'Bob'], dtype='<U3')

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[ 0  5 10 15]
[10 15]

arr5 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

arr6 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

arr7 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
arr7b [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [

## Unit 2. Optimal Data Exploration Through Pandas

### 2. 1. Pandas Exercises

In [161]:
import pandas as pd
import numpy as np
from IPython.display import display

iris_df = pd.read_csv('A_Exercises_data_iris.csv')                           # Load a data set
print(iris_df.info())                                       # Show a brief summary 
display(iris_df.head(3))                                    # Show the first n rows
display(iris_df.tail(7))                                    # Show the last n rows

# Change column names
iris_df.columns = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Variety']
display(iris_df.head(2))
print(iris_df['Sepal_Length'] is iris_df.Sepal_Length)      # Names can be fine but BEWARE of NAMING CONVENTIONS
display(iris_df[['Sepal_Length', 'Sepal_Width']])           # Displays only two columns ACCESS with [[]]

df1 = pd.DataFrame([['Tom', 15, 'Male', 'middle'], ['Alice', 10, 'Female', 'elementary']], columns=['Name', 'Age', 'Sex', 'School'])
df1.index = ['stu1', 'stu2']
df1.columns = ['student_name', 'years', 'sex2', 'school2']
display(df1)
display(df1.rename(index={'stu1': 'student1'}))
df1.rename(index={'stu2': 'student2'}, inplace=True)
display(df1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Variety
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

True


Sepal_Length  Sepal_Width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

student_name  years    sex2     school2
stu1          Tom     15    Male      middle
stu2        Alice     10  Female  elementary

student_name  years    sex2     school2
student1          Tom     15    Male      middle
stu2            Alice     10  Female  elementary

student_name  years    sex2     school2
stu1              Tom     15    Male      middle
student2        Alice     10  Female  elementary

In [162]:
exam_data = {
    'math': [90, 80, 70],
    'eng': [98, 89, 95],
    'music': [85, 95, 100],
    'science': [50, 70, 95]
}
df2 = pd.DataFrame(exam_data, index=['stu1', 'stu2', 'stu3'])
display(df2)

df3 = df2[:]                                      # Copy of the DataFrame
df3.drop('stu2', inplace=True)                    # Drop a single row
display(df3)

df4 = df2[:]                                      # Copy of the DataFrame
df4.drop(['stu2', 'stu3'], axis=0, inplace=True)  # Drop multiple rows

df5 = df2[:]                                      # Copy of the DataFrame
df5.drop('math', axis=1, inplace=True)            # Drop a column
display(df5)

print(df2.loc['stu1'])                            # Returns a row by given index
print(df2.iloc[0])                                # Returns a row by given number position in index


math  eng  music  science
stu1    90   98     85       50
stu2    80   89     95       70
stu3    70   95    100       95

C:\Users\Pablo\AppData\Local\Temp\ipykernel_16580\1579301387.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop('stu2', inplace=True)                    # Drop a single row


math  eng  music  science
stu1    90   98     85       50
stu3    70   95    100       95

C:\Users\Pablo\AppData\Local\Temp\ipykernel_16580\1579301387.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop(['stu2', 'stu3'], axis=0, inplace=True)  # Drop multiple rows
C:\Users\Pablo\AppData\Local\Temp\ipykernel_16580\1579301387.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5.drop('math', axis=1, inplace=True)            # Drop a column


eng  music  science
stu1   98     85       50
stu2   89     95       70
stu3   95    100       95

math       90
eng        98
music      85
science    50
Name: stu1, dtype: int64
math       90
eng        98
music      85
science    50
Name: stu1, dtype: int64


In [69]:
exam_data2 = {'name': ['hongildong', 'hongeeedong', 'hongsamdong'],
             'math': [90, 80, 70],
             'eng': [98, 89, 95],
             'music': [85, 95, 100],
             'science': [50, 70, 95]}
df = pd.DataFrame(exam_data2)
df.set_index('name', inplace = True)
display(df)
print(df.loc['hongildong','math'])
print(df.iloc[0, 1:3])
df['french'] = 30
df.loc['Paco'] = [100, 0, 100, 100, 100]
display(df)
df.reset_index(inplace = True)
display(df)

exam_data3 = {'name': ['stu1', 'stu2', 'stu3'],
             'math': [90, 80, 70],
             'eng': [98, 89, 95],
             'music': [85, 95, 100],
             'science': [50, 70, 95]}
df2 = pd.DataFrame(exam_data3)
display(df2.transpose())
df2.set_index(['name'])
df2.iloc[0, 3] = 800
display(df2)

math  eng  music  science
name                                  
hongildong     90   98     85       50
hongeeedong    80   89     95       70
hongsamdong    70   95    100       95

90
eng      98
music    85
Name: hongildong, dtype: int64


math  eng  music  science  french
name                                          
hongildong     90   98     85       50      30
hongeeedong    80   89     95       70      30
hongsamdong    70   95    100       95      30
Paco          100    0    100      100     100

name  math  eng  music  science  french
0   hongildong    90   98     85       50      30
1  hongeeedong    80   89     95       70      30
2  hongsamdong    70   95    100       95      30
3         Paco   100    0    100      100     100

0     1     2
name     stu1  stu2  stu3
math       90    80    70
eng        98    89    95
music      85    95   100
science    50    70    95

name  math  eng  music  science
0  stu1    90   98    800       50
1  stu2    80   89     95       70
2  stu3    70   95    100       95

In [82]:
dict_data = {'c0': [1, 2, 3],
             'c1': [4, 5, 6],
             'c2': [7, 8, 9],
             'c3': [10, 11, 12],
             'c4': [13, 14, 15]}
df = pd.DataFrame(dict_data, index = ['r0', 'r1', 'r2'])
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
display(df)
ndf = df.reindex(new_index)
display(ndf)
ndf2 = df.reindex(new_index, fill_value=0)
display(ndf2)
ndf.sort_index(ascending = False, inplace = True)
display(ndf)

c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

c0   c1   c2    c3    c4
r4  NaN  NaN  NaN   NaN   NaN
r3  NaN  NaN  NaN   NaN   NaN
r2  3.0  6.0  9.0  12.0  15.0
r1  2.0  5.0  8.0  11.0  14.0
r0  1.0  4.0  7.0  10.0  13.0

In [163]:
student1 = pd.Series({'kor': 100, 'eng': 80, 'math': 80})
student2 = pd.Series({'kor': 80, 'eng': 90, 'math': 80})

percentage     = student1 / 200 * 10
addition       = student1 + student2
substraction   = student1 - student2
multiplication = student1 * student2
division       = student1 / student2

# Creation of a DataFrame with several given pandas Series
result = pd.DataFrame([addition, substraction, multiplication, division], index=['addition', 'substraction', 'multiplication', 'division'])
display(result)

kor          eng    math
addition         180.00   170.000000   160.0
substraction      20.00   -10.000000     0.0
multiplication  8000.00  7200.000000  6400.0
division           1.25     0.888889     1.0

### 2. 2. Titanic

In [114]:
import numpy as np
import pandas as pd
from IPython.display import display
import seaborn as sns

titanic = sns.load_dataset('titanic')

In [100]:
display(titanic.head(3))
print(titanic.info())
age_and_fare = titanic.loc[:, ['age', 'fare']]        # Selects from all rows, the first 2 cols
display(age_and_fare)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None


age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

### 2. 3. Merging and Binding DataFrames

In [164]:
import numpy as np
import pandas as pd
from IPython.display import display

dfA = pd.DataFrame({
    'Name': 'Harry Potter,David Baker,John Smith,Juan Martinez,Jane Connor'.split(','),
    'Gender': 'Male Male Male Male Female'.split(),
    'Age': [23, 31, 22, 36, 30]
    
})
dfB = pd.DataFrame({
    'Name': 'John Smith,Alex Du Bois,Joanne Rowling,Jane Connor'.split(','),
    'Position': 'Intern,Team Lead,Manager,Manager'.split(','),
    'Wage': [25000, 75000, 90000, 70000]
    
})

display(pd.merge(dfA, dfB, on='Name'))                           # Default merge
display(pd.merge(dfA, dfB, left_on='Name', right_on='Name', how='inner')) # Result values are the only ones that can be combined
display(pd.merge(dfA, dfB, on='Name', how='left'))               # Takes left and joins, then fills with NaN
display(pd.merge(dfA, dfB, on='Name', how='right'))              # Takes right and joins, then fills with NaN
display(pd.merge(dfA, dfB, on='Name', how='outer'))              # Takes both and joins, then fills with NaN
display(pd.concat([dfA, dfB], axis=0, sort=True))                # Combines both data setS on ROWS, BEWARE OF INDEXES
display(pd.concat([dfA, dfB], axis=1, sort=True))                # Combines both data sets in COLS, BEWARE ON COLUMN NAMES

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

Name  Gender  Age Position     Wage
0   Harry Potter    Male   23      NaN      NaN
1    David Baker    Male   31      NaN      NaN
2     John Smith    Male   22   Intern  25000.0
3  Juan Martinez    Male   36      NaN      NaN
4    Jane Connor  Female   30  Manager  70000.0

Name  Gender   Age   Position   Wage
0      John Smith    Male  22.0     Intern  25000
1    Alex Du Bois     NaN   NaN  Team Lead  75000
2  Joanne Rowling     NaN   NaN    Manager  90000
3     Jane Connor  Female  30.0    Manager  70000

Name  Gender   Age   Position     Wage
0    Alex Du Bois     NaN   NaN  Team Lead  75000.0
1     David Baker    Male  31.0        NaN      NaN
2    Harry Potter    Male  23.0        NaN      NaN
3     Jane Connor  Female  30.0    Manager  70000.0
4  Joanne Rowling     NaN   NaN    Manager  90000.0
5      John Smith    Male  22.0     Intern  25000.0
6   Juan Martinez    Male  36.0        NaN      NaN

Age  Gender            Name   Position     Wage
0  23.0    Male    Harry Potter        NaN      NaN
1  31.0    Male     David Baker        NaN      NaN
2  22.0    Male      John Smith        NaN      NaN
3  36.0    Male   Juan Martinez        NaN      NaN
4  30.0  Female     Jane Connor        NaN      NaN
0   NaN     NaN      John Smith     Intern  25000.0
1   NaN     NaN    Alex Du Bois  Team Lead  75000.0
2   NaN     NaN  Joanne Rowling    Manager  90000.0
3   NaN     NaN     Jane Connor    Manager  70000.0

Name  Gender  Age            Name   Position     Wage
0   Harry Potter    Male   23      John Smith     Intern  25000.0
1    David Baker    Male   31    Alex Du Bois  Team Lead  75000.0
2     John Smith    Male   22  Joanne Rowling    Manager  90000.0
3  Juan Martinez    Male   36     Jane Connor    Manager  70000.0
4    Jane Connor  Female   30             NaN        NaN      NaN

In [130]:
'''
df1 = pd.read_excel('./xtock price.xlsx')
df2 = pd.read_excel('stock valuation.xlsx')
pd.merge(df1, df2)
'''

"\ndf1 = pd.read_excel('./xtock price.xlsx')\ndf2 = pd.read_excel('stock valuation.xlsx')\npd.merge(df1, df2)\n"

### 2. 4. Sorting and Multi-Index

In [166]:
import numpy as np
import pandas as pd
from IPython.display import display

df = pd.read_csv('A_Exercises_data_studentlist.csv')
display(df.head(3))
print(df.groupby(['gender', 'bloodtype'])['height'].mean())  # Filters gender and bloodT, sorting by heigth and with a reference

loc = 'L1 L1 L1 L2 L2 L1 L2 L2 L1'.split()
typ = 'A A A B B A A B B'.split()
siz = 'L L M M M S S S S'.split()
my_dict = {'Size': siz,
          'Type': typ,
          'Location': loc,
          'A': [1, 2, 2, 3, 3, 4, 5, 6, 7],
          'B': [2, 4, 5, 5, 6, 6, 8, 9, 9]}
df2 = pd.DataFrame(my_dict)
display(df2)
dfr = pd.pivot_table(df2,
                     index=['Size', 'Type'],   # Rows to group by, outer to inner
                     columns='Location',       # Cols to group by, outer to inner
                     values='B',               # Column of values to aggregate, can be a list
                     aggfunc=lambda x: sum(x), # HOW TO AGGREGATE, you can use a dictionary to aggregate to each column a different function
                     fill_value=0)             # Default filling
display(dfr)
dfr2 = pd.pivot_table(df2, index=['Size', 'Type'], columns='Location', values=['A', 'B'], fill_value=0, aggfunc={'A': np.max, 'B': np.min})
display(dfr2)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

gender  bloodtype
F       A            172.450000
        AB           170.100000
        B            158.200000
        O            164.433333
M       A            165.700000
        AB           181.050000
        B            174.550000
        O            166.200000
Name: height, dtype: float64


Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

Location   L1  L2
Size Type        
L    A      6   0
M    A      5   0
     B      0  11
S    A      6   8
     B      9   9

C:\Users\Pablo\AppData\Local\Temp\ipykernel_16580\3555802323.py:26: FutureWarning: The provided callable <function max at 0x000001CD24C3C540> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  dfr2 = pd.pivot_table(df2, index=['Size', 'Type'], columns='Location', values=['A', 'B'], fill_value=0, aggfunc={'A': np.max, 'B': np.min})
C:\Users\Pablo\AppData\Local\Temp\ipykernel_16580\3555802323.py:26: FutureWarning: The provided callable <function min at 0x000001CD24C3C680> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  dfr2 = pd.pivot_table(df2, index=['Size', 'Type'], columns='Location', values=['A', 'B'], fill_value=0, aggfunc={'A': np.max, 'B': np.min})


A     B   
Location  L1 L2 L1 L2
Size Type            
L    A     2  0  2  0
M    A     2  0  5  0
     B     0  3  0  5
S    A     4  5  6  8
     B     7  6  9  9

## Unit 3. Pandas Data Preprocessing for Optimal Model Execution

In [148]:
import pandas as pd
import numpy as np
from IPython.display import display
import seaborn as sns

df = sns.load_dataset('titanic')
display(df.head(2))

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [158]:
print(df.deck.value_counts(dropna=False))                       # Returns a Series of deck col
display(df.head().notnull())
display(df.head().isnull())
print(df.shape)
print(df.isnull().sum())                                        # Sums all columns with NaN, RETURNS WHERE THE NANS ARE
print(df.isnull().sum(axis=1))                                  # You obtain how many NaN cols are in every row
most_freq = df['embark_town'].value_counts(dropna=True).idxmax()# Returns the most frecuent value
print(df['embark_town'][325:330])     
df['embark_town'].fillna(method='ffill', inplace=True)          # Fills with the front not NaN
print(df['embark_town'][325:330])

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64


survived  pclass   sex   age  sibsp  parch  fare  embarked  class   who  \
0      True    True  True  True   True   True  True      True   True  True   
1      True    True  True  True   True   True  True      True   True  True   
2      True    True  True  True   True   True  True      True   True  True   
3      True    True  True  True   True   True  True      True   True  True   
4      True    True  True  True   True   True  True      True   True  True   

   adult_male   deck  embark_town  alive  alone  
0        True  False         True   True   True  
1        True   True         True   True   True  
2        True  False         True   True   True  
3        True   True         True   True   True  
4        True  False         True   True   True

survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0     False   False  False  False  False  False  False     False  False   
1     False   False  False  False  False  False  False     False  False   
2     False   False  False  False  False  False  False     False  False   
3     False   False  False  False  False  False  False     False  False   
4     False   False  False  False  False  False  False     False  False   

     who  adult_male   deck  embark_town  alive  alone  
0  False       False   True        False  False  False  
1  False       False  False        False  False  False  
2  False       False   True        False  False  False  
3  False       False  False        False  False  False  
4  False       False   True        False  False  False

(891, 15)
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64
0      1
1      0
2      1
3      0
4      1
      ..
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64
325      Cherbourg
326    Southampton
327    Southampton
328    Southampton
329      Cherbourg
Name: embark_town, dtype: object
325      Cherbourg
326    Southampton
327    Southampton
328    Southampton
329      Cherbourg
Name: embark_town, dtype: object


C:\Users\Pablo\AppData\Local\Temp\ipykernel_16580\626339802.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['embark_town'].fillna(method='ffill', inplace=True)          # Fills with the front not NaN


## Unit 4. Data Visualization for Various Data Scales

# Chapter 2. 