In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [7]:
arr1 = np.array([1,2,3,4,5,6])

In [9]:
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
type(arr1)

numpy.ndarray

In [13]:
arr2 = np.array([1,2,3,4,5,6])

In [15]:
arr1

array([1, 2, 3, 4, 5, 6])

In [17]:
arr2

array([1, 2, 3, 4, 5, 6])

In [19]:
id(arr1), id(arr2)

(1172533595472, 1172533594320)

In [21]:
arr3 = arr1

In [23]:
id(arr3)

1172533595472

In [25]:
arr1 is arr2

False

In [27]:
arr1 is arr3

True

In [29]:
arr1

array([1, 2, 3, 4, 5, 6])

In [31]:
arr2

array([1, 2, 3, 4, 5, 6])

In [35]:
"casa" == "gato"

False

In [37]:
"casa" == "casa"

True

In [39]:
arr1 == arr2

array([ True,  True,  True,  True,  True,  True])

In [41]:
np.array_equal(arr1, arr2)

True

In [43]:
arr4 = np.copy(arr1)

In [45]:
id(arr4)

1172570262096

In [47]:
type([1, 2, 3, 4, 5, 6])

list

In [49]:
type( (1, 2, 3, 4, 5, 6) )

tuple

In [51]:
np.array( (1, 2, 3, 4, 5, 6) )

array([1, 2, 3, 4, 5, 6])

In [53]:
{ 'one':1, 'two':2, 'three':3 }

{'one': 1, 'two': 2, 'three': 3}

In [55]:
type( { 'one':1, 'two':2, 'three':3 } )

dict

In [61]:
arr5 = np.array( { 'one':1, 'two':2, 'three':3 } )
arr5

array({'one': 1, 'two': 2, 'three': 3}, dtype=object)

In [63]:
arr1

array([1, 2, 3, 4, 5, 6])

In [67]:
arr1.shape

(6,)

In [69]:
arr1.dtype

dtype('int32')

In [71]:
arr5.shape

()

In [73]:
np.array( [1,2,3] )

array([1, 2, 3])

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [87]:
np.arange(5,20,0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [81]:
range(1000_000)

range(0, 1000000)

In [89]:
np.array( [1,2,4] )

array([1, 2, 4])

In [91]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
arr1

array([1, 2, 3, 4, 5, 6])

In [99]:
for x in arr1:
    print(x)

1
2
3
4
5
6


In [105]:
m = np.array( [[1,2,3],[4,5,6]] )
m

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
for x in m:
    print(x)

[1 2 3]
[4 5 6]


In [109]:
m.shape

(2, 3)

In [111]:
len(m)

2

In [113]:
m.size

6

In [125]:
arr6 = np.array( [True, False, 7, True, 'casa'] )
arr6

array(['True', 'False', '7', 'True', 'casa'], dtype='<U11')

In [127]:
arr6.dtype

dtype('<U11')

In [151]:
arr6 = np.array( [111, 2.3, 'hi'] )
arr6.nbytes

384

In [153]:
arr6

array(['111', '2.3', 'hi'], dtype='<U32')

In [131]:
type(arr6[0])

numpy.str_

In [135]:
arr6 = np.array( ['111', '2.3', 'hi'] )
arr6

array(['111', '2.3', 'hi'], dtype='<U3')

In [137]:
len(arr6)

3

In [139]:
arr6.size

3

In [141]:
arr6.shape

(3,)

In [143]:
arr6.ndim

1

In [145]:
arr6.nbytes

36

In [147]:
arr6.itemsize

12

In [167]:
v = np.array([1,2,300,4], dtype='int8')

C:\Users\cfp\AppData\Local\Temp\ipykernel_12532\16834820.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  v = np.array([1,2,300,4], dtype='int8')


In [169]:
v

array([ 1,  2, 44,  4], dtype=int8)

In [163]:
v.dtype

dtype('int8')

In [165]:
v.nbytes

4

In [171]:
3**1000

1322070819480806636890455259752144365965422032752148167664920368226828597346704899540778313850608061963909777696872582355950954582100618911865342725257953674027620225198320803878014774228964841274390400117588618041128947815623094438061566173054086674490506178125480344405547054397038895817465368254916136220830268563778582290228416398307887896918556404084898937609373242171846359938695516765018940588109060426089671438864102814350385648747165832010614366132173102768902855220001

In [173]:
np.array([1,2,3**1000])

array([1, 2,
       1322070819480806636890455259752144365965422032752148167664920368226828597346704899540778313850608061963909777696872582355950954582100618911865342725257953674027620225198320803878014774228964841274390400117588618041128947815623094438061566173054086674490506178125480344405547054397038895817465368254916136220830268563778582290228416398307887896918556404084898937609373242171846359938695516765018940588109060426089671438864102814350385648747165832010614366132173102768902855220001],
      dtype=object)

In [183]:
b'piña'

SyntaxError: bytes can only contain ASCII literal characters (422079741.py, line 1)

In [177]:
type(b'hola')

bytes

In [185]:
bytes([65,66,65,152])

b'ABA\x98'

In [181]:
np.array([b'hola',b'hola',b'hola'])

array([b'hola', b'hola', b'hola'], dtype='|S4')

In [197]:
a = np.array(['uno','dos','tres'], dtype='S')
print(a.nbytes)
a

UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128)

In [209]:
b = np.array(['uno','dos','tres'], dtype='<U4')
print(b.nbytes)
b

48


array(['uno', 'dos', 'tres'], dtype='<U4')

In [219]:
np.array(['uno','dos','tres']).view('uint8')

array([117,   0,   0,   0, 110,   0,   0,   0, 111,   0,   0,   0,   0,
         0,   0,   0, 100,   0,   0,   0, 111,   0,   0,   0, 115,   0,
         0,   0,   0,   0,   0,   0, 116,   0,   0,   0, 114,   0,   0,
         0, 101,   0,   0,   0, 115,   0,   0,   0], dtype=uint8)

In [215]:
np.array(['uno','dos','tres'], dtype='>U4').view('int8')

array([  0,   0,   0, 117,   0,   0,   0, 110,   0,   0,   0, 111,   0,
         0,   0,   0,   0,   0,   0, 100,   0,   0,   0, 111,   0,   0,
         0, 115,   0,   0,   0,   0,   0,   0,   0, 116,   0,   0,   0,
       114,   0,   0,   0, 101,   0,   0,   0, 115], dtype=int8)

In [217]:
np.array(['uno','dos','tres'], dtype='S4').view('int8')

array([117, 110, 111,   0, 100, 111, 115,   0, 116, 114, 101, 115],
      dtype=int8)

In [231]:
np.linspace(20,30,21,dtype='float32')

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. ],
      dtype=float32)

In [243]:
np.geomspace(1,100,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [239]:
import math

In [245]:
np.logspace(math.log10(1), math.log10(100), 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [249]:
np.zeros( (3,4), dtype=bool )

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [253]:
np.ones( (3,4) ) * 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [255]:
np.array([[1,2,3],[4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [259]:
a = np.array([[1,2,3],[4,5,6]])

In [261]:
a.dtype

dtype('int32')

In [263]:
a.shape

(2, 3)

In [265]:
len(a)

2

In [267]:
a.size

6

In [269]:
a.ndim

2

In [271]:
a.itemsize

4

In [273]:
a.nbytes

24

In [275]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [277]:
a[0]

array([1, 2, 3])

In [279]:
a[1]

array([4, 5, 6])

In [281]:
a[-1]

array([4, 5, 6])

In [283]:
a[-2]

array([1, 2, 3])

In [285]:
a[0][2]

3

In [287]:
a[0,2]

3

In [289]:
a.item(0,2)

3

In [291]:
b = np.array( {1:2, 3:4} )

In [293]:
b

array({1: 2, 3: 4}, dtype=object)

In [295]:
b.shape

()

In [297]:
b.ndim

0

In [303]:
b[]

SyntaxError: invalid syntax (2061897702.py, line 1)

In [305]:
b.item()

{1: 2, 3: 4}

In [307]:
a = np.array([1,2,3])

In [309]:
a

array([1, 2, 3])

In [311]:
a.dtype

dtype('int32')

In [313]:
b = a.astype('float32')

In [315]:
b

array([1., 2., 3.], dtype=float32)

In [317]:
c = b.astype('float32')

In [319]:
c

array([1., 2., 3.], dtype=float32)

In [321]:
id(b),id(c)

(1172598600400, 1172598599728)

In [337]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [339]:
b = a.reshape(15)

In [341]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [343]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [345]:
a is b

False

In [347]:
id(a),id(b)

(1172598590320, 1172598600304)

In [349]:
a.shape

(3, 5)

In [351]:
b.shape

(15,)

In [355]:
a[2,1] = 1000

In [357]:
b

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       1000,   12,   13,   14])

In [359]:
np.shares_memory(a,b)

True

In [361]:
lista1 = [10,20,30]

In [363]:
lista2 = lista1[:]

In [365]:
lista2

[10, 20, 30]

In [367]:
lista2[1] += 1000

In [369]:
lista2

[10, 1020, 30]

In [371]:
lista1

[10, 20, 30]

In [373]:
array1 = np.array([10,20,30])

In [375]:
array2 = array1[:]

In [377]:
id(array1), id(array2)

(1172598588688, 1172598587728)

In [379]:
np.shares_memory(array1, array2)

True

In [383]:
array1[1] += 1000

In [385]:
array1

array([  10, 1020,   30])

In [387]:
array2

array([  10, 1020,   30])

In [391]:
a = np.arange(70).reshape(7,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [395]:
b = a[:5,:5]
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [397]:
c = np.copy(b)

In [399]:
np.shares_memory(a,b)

True

In [401]:
np.shares_memory(a,c)

False

In [409]:
np.random.randint(5,10, (7,5))

array([[6, 5, 7, 7, 6],
       [5, 7, 9, 5, 6],
       [9, 7, 6, 5, 7],
       [6, 8, 7, 8, 6],
       [8, 8, 8, 8, 9],
       [7, 5, 8, 9, 8],
       [8, 8, 6, 5, 7]])

In [413]:
np.arange(10) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [415]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [423]:
[i for i in range(10)] * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [421]:
["hola"] * 2

['hola', 'hola']

# Append y delete

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [6]:
b = np.append(a, [4,5,6])

In [8]:
b

array([1, 2, 3, 4, 5, 6])

In [10]:
a

array([1, 2, 3])

In [14]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [18]:
b = np.append(a, [[9,9]], axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [20]:
c = np.append(a, [[9],[9]], axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

In [24]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.delete(a, 0, axis=0)

array([[4, 5, 6]])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.delete(a, 0, axis=1)

array([[2, 3],
       [5, 6]])

In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [40]:
arr1+arr2

array([5, 7, 9])

In [42]:
arr1.ndim

1

In [44]:
arr1.size

3

In [46]:
arr1.shape

(3,)

In [48]:
arr1-arr2

array([-3, -3, -3])

In [50]:
arr1*arr2

array([ 4, 10, 18])

In [52]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [54]:
b = np.array([1,2,3])

In [56]:
3*b

array([3, 6, 9])

In [58]:
b

array([1, 2, 3])

In [60]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [62]:
np.tile(b, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [76]:
c = np.arange(9)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
%%timeit

c = np.arange(1000000)

791 μs ± 9.31 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [74]:
%%timeit

c.reshape(2,500000)

124 ns ± 1.15 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [82]:
c = c.reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
np.tile(c, 3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [86]:
arr2

array([4, 5, 6])

In [88]:
arr2**2

array([16, 25, 36])

In [90]:
arr1 / (arr2**2)

array([0.0625    , 0.08      , 0.08333333])

# operadores lógicos

In [93]:
arr3 = np.array([10,20,30,40])

In [95]:
arr3 > 10

array([False,  True,  True,  True])

In [97]:
x = np.array([0,1,2,3])

In [99]:
x**3

array([ 0,  1,  8, 27], dtype=int32)

In [101]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [103]:
np.mean(x)

1.5

In [105]:
np.sum(x)

6

In [107]:
np.cumsum(x)

array([0, 1, 3, 6])

In [109]:
np.argmax(x)

3

In [111]:
x

array([0, 1, 2, 3])

In [113]:
x.mean()

1.5

In [115]:
x.cumsum()

array([0, 1, 3, 6])

In [117]:
x_mean = x.mean()

In [119]:
x - x_mean

array([-1.5, -0.5,  0.5,  1.5])

In [121]:
(x-x_mean)**2

array([2.25, 0.25, 0.25, 2.25])

In [123]:
x.std()

1.118033988749895

In [125]:
x.var()

1.25

In [127]:
x.mean()

1.5

In [129]:
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [131]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
x.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
x.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
x.reshape(-1, 4)

ValueError: cannot reshape array of size 6 into shape (4)

In [139]:
x.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
x

array([1, 2, 3, 4, 5, 6])

In [143]:
x = x.reshape(2,3)

In [145]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
x.mean(axis=1)

array([2., 5.])

In [149]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

# numeros aleatorios

In [152]:
np.random.seed(125)

In [154]:
np.random.randint(10)

2

In [170]:
np.random.randint(5,10)

8

In [172]:
np.random.randint(1, 10, size=(3,))

array([6, 1, 5])

In [174]:
np.random.randint(1, 10, size=(3,2))

array([[3, 1],
       [8, 3],
       [8, 6]])

In [189]:
while True:
    num = np.random.randint(1,11)
    print(num)
    if num ==10:
        break

4
2
4
1
5
1
10


In [191]:
a = np.random.randint(1,11,size=
                      )

In [193]:
a.size

1000

In [195]:
a.shape

(1000,)

In [197]:
a

array([ 4,  1,  4,  7,  8,  9,  7,  9,  1, 10,  1,  6,  1,  3,  7,  3,  4,
        8,  8,  3,  1,  6,  6,  7,  7,  7,  5,  7,  5,  5,  9,  4,  9, 10,
        4,  9,  3,  9,  6, 10,  7,  9,  3, 10,  7, 10,  4, 10,  5,  7,  1,
        8,  2,  2,  5,  5,  9,  9,  5,  4, 10,  1,  2,  6,  2,  2,  1,  9,
        2,  5,  9,  2,  4,  7, 10,  4,  6,  9,  5,  6,  8,  8,  4,  2,  7,
        1,  3,  1,  9,  4,  7,  8,  8,  7,  1,  9,  8,  7,  2,  5,  1,  3,
        6,  4,  7, 10,  7,  9,  6,  3, 10, 10,  8,  8,  3, 10,  3,  4,  1,
        8,  9,  6,  8,  9,  3,  2, 10,  1,  2,  7, 10,  4,  7,  8,  1, 10,
        5,  7,  3,  3,  6,  2,  6,  3,  6, 10, 10,  8,  9,  2,  3,  9,  3,
        8,  1,  9, 10,  9,  9,  2,  8,  4,  7,  3,  2,  5,  8,  2, 10,  5,
        1,  5,  2,  1,  2,  4,  6,  5,  2,  1,  5,  4,  9,  7,  8,  8, 10,
       10,  1,  1,  6,  5, 10,  8,  7,  2,  9, 10,  4,  6,  5,  7,  2,  9,
        4,  3, 10,  2,  6,  5,  9,  1,  1,  1,  6,  6,  1,  2,  9,  4,  7,
        7,  2, 10,  8,  8

In [199]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [201]:
np.median(a)

6.0

In [205]:
np.sum(a)

5503

In [207]:
a.sum()

5503

In [209]:
np.round(np.var(a), 2)

8.36

In [211]:
np.var(a)

8.357990999999998

In [213]:
np.round(np.mean(a),2)

5.5

In [215]:
np.max(a)

10

In [217]:
np.min(a)

1

In [219]:
np.array(set(a))

array({1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, dtype=object)

In [221]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [223]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [225]:
np.argmax(a)

4

In [227]:
np.argmin(a)

1

In [229]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [231]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [233]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [235]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [237]:
A @ B

array([[0, 1],
       [6, 7]])

In [239]:
A

array([[0, 1],
       [2, 3]])

In [241]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [243]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [245]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [247]:
np.linalg.det(A)

-2.0

# Indexing y slicing

In [250]:
a = np.array([0,1,2,3])
b = np.array([[0,1,2,3],[4,5,6,7], [8,9,10,11]])

In [252]:
a

array([0, 1, 2, 3])

In [254]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [256]:
a[0]

0

In [258]:
b[0]

array([0, 1, 2, 3])

In [260]:
b[0][2]

2

In [262]:
b[0,2]

2

In [264]:
a1 = np.array([0,10,20,30,40,50])

In [266]:
a1[5]

50

In [268]:
a1[5] = 77

In [272]:
a1

array([ 0, 10, 20, 30, 40, 77])

In [276]:
a1[[1,3,5]]

array([10, 30, 77])

In [282]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [284]:
a2[0,2]

30

In [286]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [290]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [293]:
a2[[0,2],[0,1]]

array([10, 80])

# condicionales

In [296]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [298]:
a[a>3]

array([4, 5, 6])

In [300]:
a>3

array([False, False, False,  True,  True,  True])

In [302]:
a[a%2 == 0]

array([2, 4, 6])

In [304]:
b1 = np.array([0,10,20,30,40,50])
b1

array([ 0, 10, 20, 30, 40, 50])

In [306]:
b1[1:4]

array([10, 20, 30])

In [308]:
b1[:3]

array([ 0, 10, 20])

In [310]:
b1[3:]

array([30, 40, 50])

In [312]:
arr2d = np.arange(1,10).reshape(3,3)

In [314]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [316]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [318]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [320]:
arr2d[:2, 2]

array([3, 6])

In [322]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [324]:
names = np.array(['Bob','Joe', 'Tom', 'Bob','Tom','Joe','Joe'])

In [326]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U3')

In [328]:
arr = np.empty((8,4))
arr

array([[7.91570869e-312, 1.06718180e-321, 0.00000000e+000,
        0.00000000e+000],
       [7.91504430e-312, 5.02034658e+175, 3.76113149e+179,
        5.68421450e-062],
       [4.35291425e-061, 4.16163550e-061, 1.66759031e-047,
        7.75208037e-144],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        1.04918675e-153],
       [7.69165785e+218, 5.04621343e+180, 1.04917822e-153,
        9.08366793e+223],
       [3.76113149e+179, 5.68421450e-062, 4.35291425e-061,
        4.16163550e-061],
       [1.04914907e-153, 1.94918966e-153, 3.11549848e-033,
        4.17576316e-057],
       [6.38560205e-067, 2.59027896e-144, 7.79952704e-143,
        5.81186265e+294]])

In [330]:
np.zeros((8,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [332]:
np.ones((8,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [334]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [336]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [338]:
arr[[-3, -5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [340]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [342]:
arr2%5==0

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False])

In [344]:
arrMask = arr2%5==0

In [346]:
arr2[arrMask]

array([ 0,  5, 10, 15])

In [348]:
arr2[arr2%5==0]

array([ 0,  5, 10, 15])

In [350]:
arr2>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [358]:
arrMask2 = arr2>=10

In [360]:
arr2[arrMask & arrMask2]

array([10, 15])

# Transposiciones y swapping

In [363]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [365]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [367]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [371]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [373]:
arr.T.shape, arr.shape

((5, 3), (3, 5))

In [375]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [377]:
arr1.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [379]:
arr1.transpose((0,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [381]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [385]:
arr1.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [387]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [389]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [391]:
arr.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [393]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [395]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [399]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [401]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [403]:
arr.transpose(0,2,1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])